# Generated by Django 6.0.6 on 2026-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('bioId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bios',
            },
        ),
    ]
